version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    container_name: postgres
    env_file:
      - './env/.env.dev'
    ports:
      - '54321:${POSTGRES_PORT}'
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_NAME}
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:7.2
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres

  app:
    build:
      dockerfile: docker/app.Dockerfile
      context: .
    container_name: app
    ports:
      - '8000:8000'
    volumes:
      - ./:/home/code/app
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data: