# Generated by Django 4.2.7 on 2023-11-17 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_dog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dog',
        ),
    ]
